# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chariot < Formula
  desc "Deploy and manage enterprise agent fleets from your terminal"
  homepage "https://app.chariots.sh"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Immortal-Protocols/Chariot-CLI/releases/download/v0.1.7/chariot_0.1.7_darwin_amd64.tar.gz"
      sha256 "ef1f3a9649bd4413bd54ac1cf811efa8b6167120065153f75084741c6574f76b"

      define_method(:install) do
        bin.install "chariot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Immortal-Protocols/Chariot-CLI/releases/download/v0.1.7/chariot_0.1.7_darwin_arm64.tar.gz"
      sha256 "48117eeeba3947e0d6e65c8632174f35b35eadd455346536eb139ba81bb305f6"

      define_method(:install) do
        bin.install "chariot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Immortal-Protocols/Chariot-CLI/releases/download/v0.1.7/chariot_0.1.7_linux_amd64.tar.gz"
      sha256 "dc392fe18de137f2a60499f06c67f1d7147ced86c44feca6a5e7765775870e67"
      define_method(:install) do
        bin.install "chariot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Immortal-Protocols/Chariot-CLI/releases/download/v0.1.7/chariot_0.1.7_linux_arm64.tar.gz"
      sha256 "89bbbdf8ef4a56ace25c88cb30a3351685fee1ba25b226387ca3acc41ee7f77a"
      define_method(:install) do
        bin.install "chariot"
      end
    end
  end

  test do
    system "#{bin}/chariot", "version"
  end
end
