# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chariot < Formula
  desc "Deploy and manage enterprise agent fleets from your terminal"
  homepage "https://app.chariots.sh"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Immortal-Protocols/Chariot-CLI/releases/download/v0.1.0/chariot_0.1.0_darwin_amd64.tar.gz"
      sha256 "3bd665333aca05045143e9fd9d6df576add594be53a8bb06687d9edffc9eb81d"

      define_method(:install) do
        bin.install "chariot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Immortal-Protocols/Chariot-CLI/releases/download/v0.1.0/chariot_0.1.0_darwin_arm64.tar.gz"
      sha256 "ff4a6e7b74627239d166050b0f611ce315d8125daf629e83cddeab7b2cc130e3"

      define_method(:install) do
        bin.install "chariot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Immortal-Protocols/Chariot-CLI/releases/download/v0.1.0/chariot_0.1.0_linux_amd64.tar.gz"
      sha256 "7d2f0969b2904d5a68c6affae1ed05f065be0a367f425d2ff820f081941368c5"
      define_method(:install) do
        bin.install "chariot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Immortal-Protocols/Chariot-CLI/releases/download/v0.1.0/chariot_0.1.0_linux_arm64.tar.gz"
      sha256 "d4241d2f7af6746edafeb5bb36fd281e20f0cc583b9535adfac52bac1d679309"
      define_method(:install) do
        bin.install "chariot"
      end
    end
  end

  test do
    system "#{bin}/chariot", "version"
  end
end
