# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chariot < Formula
  desc "Deploy and manage enterprise agent fleets from your terminal"
  homepage "https://app.chariots.sh"
  version "0.1.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Immortal-Protocols/Chariot-CLI/releases/download/v0.1.12/chariot_0.1.12_darwin_amd64.tar.gz"
      sha256 "7608611e1b35f4805aac3192408406a6c112638e5dfad2afd0af3813641f7b45"

      define_method(:install) do
        bin.install "chariot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Immortal-Protocols/Chariot-CLI/releases/download/v0.1.12/chariot_0.1.12_darwin_arm64.tar.gz"
      sha256 "41b0c20a98824277403a58df85b32ad48c5bca70aa51babdd68ebad627ce48a8"

      define_method(:install) do
        bin.install "chariot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Immortal-Protocols/Chariot-CLI/releases/download/v0.1.12/chariot_0.1.12_linux_amd64.tar.gz"
      sha256 "124e37bab073a64f02418f1bcc1475322d08650c6d2249a0e54b3a064a65a219"
      define_method(:install) do
        bin.install "chariot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Immortal-Protocols/Chariot-CLI/releases/download/v0.1.12/chariot_0.1.12_linux_arm64.tar.gz"
      sha256 "3f51589920e6fe101ce67b0aaad045c4add2315071f58cfcbb10d2bc3e5a102b"
      define_method(:install) do
        bin.install "chariot"
      end
    end
  end

  test do
    system "#{bin}/chariot", "version"
  end
end
